apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application

metadata:
  name: matrikkel-ekstern-data-ingestor
  namespace: matrikkel-prodtest

spec:
  image: "{{ image }}"
  port: 8050
  ingresses:
    - matrikkel-ekstern-data-ingestor-prodtest.atkv3-prod.kartverket-intern.cloud
  replicas: 1

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi

  liveness:
    port: 8050
    path: /internal/isAlive
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3
  readiness:
    port: 8050
    path: /internal/isReady
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3
  prometheus:
    port: 8050
    path: /internal/metrics
    allowAllMetrics: true

  azure:
    application:
      enabled: true

  accessPolicy:
    outbound:
      rules:
        - application: matrikkel-kafka-light

  env:
    - name: VERSION
      value: "{{ version }}"
    - name: KAFKA_BROKER_URL
      value: "http://matrikkel-kafka-light.matrikkel-prodtest:8081"
    - name: KAFKA_BROKER_SCOPE
      value: "atkv3-prod:matrikkel-prodtest:matrikkel-kafka-light"
    - name: ENVIRONMENT
      value: "staging"