[versions]
kotlin = "2.4.0"
logback = "1.5.37"
mockk = "1.14.5"
junitVersion = "6.1.3"
assertk = "0.28.1"
kotlinxCoroutinesTest = "1.11.0"
heimdall-common-utils = "1.2026.09.22-11.33-3cc3657"

[libraries]
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.19" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logstash = { module = "net.logstash.logback:logstash-logback-encoder", version = "9.0" }
ktorUtils = { module = "no.kartverket.heimdall.common:ktor-utils", version.ref = "heimdall-common-utils" }
kotlin-utils = { module = "no.kartverket.heimdall.common:kotlin-utils", version.ref = "heimdall-common-utils" }
micrometerPrometheus = { module = "io.micrometer:micrometer-registry-prometheus", version = "1.17.0" }
kafka-light = { module = "no.kartverket.kafkalight:client", version = "2026.09.18-06.50-a8e4ad5"}
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitVersion" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitVersion" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
feature-flags = { module = "no.kartverket.heimdall.common:feature-flags", version.ref = "heimdall-common-utils" }

[bundles]
testEcosystem = [
    "logback-classic",
    "mockk",
    "junitApi",
    "junitEngine",
    "assertk",
    "kotlinx-coroutines-test",
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
